---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart metrics tunnel
  ansible.builtin.systemd:
    name: dut-metrics-tunnel-openwrt-one
    state: restarted

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
